export const projects = [
 {slug:'rabbithole',name:'Rabbithole',category:'AI',status:'Live',description:'An AI encyclopedia with personalized search and discovery.',tags:['AI agents','Vector embeddings','Android','Capacitor'],image:'/projects/rabbithole.gif'},
 {slug:'kit',name:'Kit OS',category:'AI',status:'Alpha',description:'Small, purpose-built AI apps, with their own interfaces and saved context.',tags:['Generative UI','Micro-apps','Gemini'],image:'/projects/kit-thumbnail.png'},
 {slug:'foodbuddy',name:'Foodbuddy',category:'AI',status:'Unmaintained · private',description:'AI nutrition tracking with an accountability partner and social features.',tags:['Multimodal AI','Google Cloud'],image:'/projects/foodbuddy-thumbnail.PNG'},
 {slug:'pdf-proofreader',name:'PDF Proofreader',category:'Tools',status:'Unmaintained · public',description:'A CrewAI workflow for proofreading and styling long documents.',tags:['CrewAI','Prompt engineering'],image:'/projects/pdf-proofreader-thumbnail.png'},
 {slug:'fileops',name:'FileOps',category:'Tools',status:'Private · evolving',description:'An MCP server for reliable, AI-enriched metadata search across files.',tags:['MCP','Semantic search','Node.js'],image:'/projects/fileops-cover.png',longform:`<p>FileOps started with a practical question: how should an agent find the right file when filenames and folders are not enough? The project adds a searchable metadata layer to a local file system, so an agent can retrieve useful context without guessing paths.</p><h2>What I was exploring</h2><p>The work sits between a file manager and an MCP server. Metadata is extracted, indexed, and returned through a small tool surface that is easier for an agent to use than a pile of shell commands.</p><h2>Why it matters</h2><p>Reliable retrieval is a prerequisite for useful agent workflows. FileOps keeps the source files where they are while making their structure and meaning easier to query.</p>`},
 {slug:'blinkit-tools',name:'Blinkit Tools',category:'Tools',status:'Private · prototype',description:'A controlled automation layer for grocery discovery, carts, and payment handoffs.',tags:['Automation','Browser flows','UPI'],image:'/projects/blinkit-tools-cover.png',longform:`<p>Blinkit Tools is a prototype for making a grocery workflow legible to an agent: find items, build a cart, choose a saved address, and stop at an explicit payment checkpoint.</p><h2>Designing the handoff</h2><p>The interesting part is the boundary between useful automation and an action that should stay with the person. Each stage is represented as a visible state, so the system can report what it knows and wait when a human decision is required.</p><h2>Current state</h2><p>This is a private prototype used to test the interaction model and failure handling before any wider release.</p>`},
 {slug:'openupi',name:'OpenUPI',category:'AI',status:'Private · testing',description:'A native voice concierge for Indian commerce and payments, with a careful human approval step.',tags:['SwiftUI','Voice AI','UPI','iOS'],image:'/projects/openupi-cover.png',longform:`<p>OpenUPI is a native iOS voice concierge for Indian digital commerce and payments. It brings a bilingual Hindi and English interface together with grocery discovery, QR scanning, and a path to legacy UPI rails.</p><h2>One conversation, several surfaces</h2><p>The prototype connects a voice-first interaction to focused interfaces: a Blinkit grocery engine, a UPI QR scanner, and a hardware bridge for GSM and USSD experiments. Fabits wealth flows are part of the same exploration.</p><h2>The constraint</h2><p>Money-moving actions need a clear verbal confirmation. The assistant can prepare a flow, but it does not silently approve a payment on someone’s behalf.</p>`},
 {slug:'duomaxxing',name:'Duomaxxing',category:'AI',status:'Android + iOS · testing',description:'A paired habit and challenge app built around check-ins, milestones, and shared momentum.',tags:['Android','iOS','Social habits'],image:'/projects/duomaxxing-cover.png',longform:`<p>Duomaxxing is a paired challenge app for people who want a little more structure and a little more accountability. It is in testing on Android and iOS.</p><h2>Shared progress</h2><p>People set criteria, check in, and see progress across daily and monthly views. Feeds, milestones, locations, photos, notifications, and small companion characters make the routine feel social without turning it into a leaderboard.</p><h2>What is still changing</h2><p>The testing phase is focused on the rhythm of a check-in: what should be visible, what should stay private, and how a pair can recover after missing a day.</p>`},
 {slug:'dwaar',name:'Dwaar',category:'AI',status:'Private · testing',description:'A voice-first Android keyboard and device assistant inspired by Wispr Flow and Heyclicky.',tags:['Android','Voice input','On-device safety'],image:'/projects/dwaar-cover.png',longform:`<p>Dwaar is a voice-first Android keyboard and device assistant inspired by Wispr Flow and Heyclicky. It brings a floating keyboard, voice controls, and accessibility actions into one place.</p><h2>Close to the device</h2><p>The prototype combines local screen summarisation, a floating cursor, speech input and output, and a safety layer that can decide when an action needs more context. It is designed to stay useful when an agent cannot rely on a perfect app integration.</p><h2>Why a keyboard</h2><p>A keyboard is available across the phone. That makes it a practical home for voice, text, and small actions without forcing every app to grow its own assistant.</p>`},
 {slug:'blindpay-esp32',name:'BlindPay ESP32',category:'Hardware',status:'Prototype',description:'A voice-first UPI interface paired with an ESP32 and SIM800 bridge for accessible payment experiments.',tags:['ESP32','SIM800L','Voice AI','Accessibility'],image:'/projects/blindpay-esp32-cover.png',longform:`<p>BlindPay combines a blind-friendly voice interface with a small hardware bridge for UPI experiments. The browser experience handles speech and feedback; an ESP32 and SIM800 module explore how the same flow might work over a cellular connection.</p><h2>One hardware project</h2><p>The prototype is intentionally small: microphone in, clear voice feedback out, and a constrained route toward QR or USSD payment states. The point is to test the interaction and the reliability of the bridge, not to hide complexity behind a shiny demo.</p><h2>Safety first</h2><p>Payment actions remain explicit. The interface can prepare the next step, while the person stays in control of confirmation.</p>`},
 {slug:'gitship-news',name:'Gitship News',category:'Tools',status:'Public',description:'A newspaper-style static site generated from an autonomous newsroom workflow.',tags:['Static sites','Publishing','Agents'],url:'https://github.com/mansanitizer/gitship-news'}
];
