import {writeFileSync,readFileSync} from 'node:fs';
import {projects} from '../src/content/projects.js';
import {workData} from '../src/content/work.js';
const details=JSON.parse(readFileSync(new URL('../src/content/project-details.json',import.meta.url)));
const root=new URL('../',import.meta.url);
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const arrow='<span aria-hidden="true">↗</span>';
const visualCovers={fileops:'/projects/fileops-cover.svg', 'blinkit-tools':'/projects/blinkit-tools-cover.svg', openupi:'/projects/openupi-cover.svg', duomaxxing:'/projects/duomaxxing-cover.svg', dwaar:'/projects/dwaar-cover.svg', 'blindpay-esp32':'/projects/blindpay-esp32-cover.svg'};
const work=[
 ['product-launches','Mutual fund baskets','Investing by goal, with an admin dashboard to manage allocations.','2×','AUM growth','mf-baskets.png','Product strategy · Investing'],
 ['user-growth','Mutual fund search','Fund discovery and filtering for investors who know what they’re looking for.','60%','MAU increase','mf-direct.png','Discovery · Growth'],
 ['compliance','Brand & interface redesign','A new design system and interface for the Fabits platform.','4 → 7','NPS score','brand-revamp.png','Design systems · UX'],
 ['ux-enhancement','KYC & authentication','Identity verification, onboarding, and internal authentication.','','','kyc-auth.png','Onboarding · Compliance'],
 ['upi-autopay','Events & notifications','The infrastructure behind product analytics and user communication.','','','events-notifications.png','Infrastructure · Retention'],
 ['analytics','IPO & SGB investments','Application and investment flows for IPOs and Sovereign Gold Bonds.','','','ipo-sgb.png','Investment workflows']
];
function shell(title,content,page='home',description='Ashar Rai Mujeeb is a product manager at Fabits in Bengaluru. Explore fintech work, AI projects, hardware experiments, and product case studies.'){
 const path=page==='home'?'':page==='playground'?'playground.html':`projects/${page}.html`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Ashar Rai Mujeeb</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#f8f9fb"><link rel="canonical" href="https://ashar.site/${path}"><meta property="og:title" content="${escape(title)} — Ashar Rai Mujeeb"><meta property="og:description" content="${escape(description)}"><meta property="og:image" content="https://ashar.site/og-image.jpg"><meta property="og:url" content="https://ashar.site/${path}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;550;600;650;700;750&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet"><script type="module" src="/src/site.js"></script></head><body data-page="${page}"><a class="skip" href="#main">Skip to content</a>
 <aside class="rail"><a class="monogram" href="/" aria-label="Ashar Rai Mujeeb home">ar<span>m.</span></a><span class="rail-caption">PRODUCT MANAGER & BUILDER</span><a class="rail-bottom" href="mailto:asharrm18@gmail.com" aria-label="Email Ashar">${arrow}</a></aside>
 <div class="site"><header class="topbar"><a class="small identity" href="/">ASHAR RAI MUJEEB</a><nav aria-label="Main navigation"><a href="/#work">Work <sup>06</sup></a><a href="/playground.html" ${page==='playground'?'aria-current="page"':''}>Projects <sup>${String(projects.length).padStart(2,'0')}</sup></a><a href="/#about">About</a><a href="/#contact">Contact ${arrow}</a></nav><button class="icon-button" id="settings-open" aria-label="Appearance and sharing settings" aria-haspopup="dialog">◐</button></header>
 <main id="main">${content}</main>
 <footer><a href="/" class="footer-name">Ashar Rai Mujeeb<span>Product Manager · Bengaluru, India</span></a><div><a href="https://www.linkedin.com/in/0xtr0jan/" target="_blank" rel="noopener noreferrer">LinkedIn ${arrow}</a><a href="mailto:asharrm18@gmail.com">Email ${arrow}</a><button class="text-button" id="share-copy">Copy site link ${arrow}</button></div><p class="small">© ${new Date().getFullYear()} · <button class="text-button" id="shortcuts-open">Keyboard shortcuts</button></p></footer></div>
 <dialog id="settings-dialog" class="small-dialog" aria-label="Appearance and sharing"><div class="dialog-top"><span class="small">PREFERENCES</span><button class="icon-button" data-close aria-label="Close settings">×</button></div><h2>Appearance & sharing</h2><div class="setting-row"><label for="theme-setting">Dark appearance</label><input id="theme-setting" type="checkbox" role="switch"></div><div class="setting-row"><label for="contrast-setting">High contrast</label><input id="contrast-setting" type="checkbox" role="switch"></div><div class="setting-row"><label for="tracking-setting">Allow analytics</label><input id="tracking-setting" type="checkbox" role="switch"></div><div class="setting-row"><span>Accent</span><div class="swatches"><button data-accent="#3155e7" style="--swatch:#3155e7" aria-label="Blue accent"></button><button data-accent="#8b4bce" style="--swatch:#8b4bce" aria-label="Violet accent"></button><button data-accent="#17755d" style="--swatch:#17755d" aria-label="Green accent"></button><button id="random-accent" aria-label="Random accent">↻</button></div></div><p class="small">SHARE THIS PORTFOLIO</p><div class="share-links"><a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fashar.site" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://twitter.com/intent/tweet?url=https%3A%2F%2Fashar.site" target="_blank" rel="noopener noreferrer">Twitter ↗</a><a href="https://wa.me/?text=https%3A%2F%2Fashar.site" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a></div></dialog>
 <dialog id="shortcuts-dialog" class="small-dialog" aria-label="Keyboard shortcuts"><div class="dialog-top"><span class="small">KEYBOARD</span><button class="icon-button" data-close aria-label="Close shortcuts">×</button></div><h2>Get around quickly.</h2><dl class="shortcut-list"><div><dt>Contact</dt><dd><kbd>Z</kbd> <kbd>C</kbd></dd></div><div><dt>Change theme</dt><dd><kbd>Z</kbd> <kbd>N</kbd></dd></div><div><dt>Random accent</dt><dd><kbd>Z</kbd> <kbd>X</kbd></dd></div><div><dt>Download CV</dt><dd><kbd>C</kbd> <kbd>V</kbd></dd></div><div><dt>Report a problem</dt><dd><kbd>Z</kbd> <kbd>R</kbd></dd></div><div><dt>This menu</dt><dd><kbd>/</kbd></dd></div><div><dt>Close dialog</dt><dd><kbd>Esc</kbd></dd></div></dl></dialog><div class="toast" id="toast" role="status"></div></body></html>`.replace(/[ \t]+$/gm, '');
}
function projectCard(p,i){const href=p.url||`/projects/${p.slug}.html`;const image=visualCovers[p.slug]||p.image;const media=image?`<img src="${image}" alt="${p.name} project preview" loading="lazy">`:p.video?`<video src="${p.video}" poster="${p.poster||''}" muted playsinline preload="metadata" aria-label="${p.name} preview"></video>`:`<div class="project-placeholder" aria-hidden="true"><span>${p.category}</span></div>`;return `<a class="project-card" href="${href}" ${p.url?'target="_blank" rel="noopener noreferrer"':''} data-category="${p.category}" data-search="${escape([p.name,p.description,...p.tags].join(' ').toLowerCase())}"><div class="project-media">${media}<span class="project-index small">${String(i+1).padStart(2,'0')} / ${p.category.toUpperCase()}</span><span class="round-arrow">↗</span></div><div class="project-heading"><h3>${p.name}</h3><span class="status ${p.status==='Live'?'live':''}">${p.status}</span></div><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></a>`;}
function slideTitle(html,i){const match=html.match(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/i);const title=(match?.[1]||`Project note ${i+1}`).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();return title||`Project note ${i+1}`;}
function renderSlides(slides){return slides.map((slide,i)=>{if(typeof slide!=='string') return '';const label=slideTitle(slide,i);return `<details class="presentation-slide" ${i===1?'open':''}><summary><span><b>${String(i+1).padStart(2,'0')}</b> ${label}</span><span aria-hidden="true">+</span></summary><div class="slide-render">${slide}</div></details>`}).join('');}
const contact=`<section id="contact" class="contact-section"><div class="section-label small"><span>04 / CONTACT</span><span>BENGALURU, INDIA</span></div><h2>Let’s talk<span class="accent">.</span> <a href="mailto:asharrm18@gmail.com" aria-label="Email Ashar">↗</a></h2><div class="contact-columns"><div><p>For product roles, collaborations,<br>or a project you want to discuss.</p><a class="email-link" href="mailto:asharrm18@gmail.com">asharrm18@gmail.com</a><div class="contact-other"><a href="tel:+917378666101">+91 73786 66101</a><a href="https://wa.me/917378666101" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><a href="https://www.linkedin.com/in/0xtr0jan/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><form id="contact-form" novalidate><label for="contact-input">Or leave your contact details.</label><div class="input-row"><input id="contact-input" name="contact" placeholder="Your email or phone number" autocomplete="email" aria-describedby="contact-status" required><button class="button primary" type="submit">Send ↗</button></div><p id="contact-status" role="status">I’ll get back to you.</p></form></div></section>`;
const home=`<section class="hero-new"><div class="hero-meta small"><span><i class="dot"></i> PRODUCT MANAGER AT FABITS</span><span>FINTECH / AI / HARDWARE</span></div><h1>Ashar Rai<br><span class="surname">Mujeeb<span class="accent">.</span><svg id="seed-mark" viewBox="0 0 180 180" aria-hidden="true"></svg></span></h1><div class="hero-intro"><p>I build investment products.<br>And things I wish existed.</p><div><p>Product manager in Bengaluru. Previously in law.<br>Currently working on mutual funds at Fabits.</p><a class="button primary" href="#work">Explore my work <span>↓</span></a><a class="inline-link" href="/cv.pdf" download="Ashar-Rai-Mujeeb-CV.pdf">Download CV ↗</a></div></div><div class="hero-baseline small"><span>BENGALURU, INDIA · PRODUCT & TECHNOLOGY</span><span>SCROLL TO SEE THE WORK ↓</span></div></section>
<section id="work" class="work-section"><div class="section-label small"><span>01 / SELECTED WORK</span><span>FABITS · NOV 2023 — PRESENT</span></div><div class="section-heading"><h2>At work.</h2><p>Investment products, from the first<br>wireframe to the flow people use.</p></div><div class="outcomes">${[['2×','Assets under management'],['60%','Monthly active user increase'],['4 → 7','Net Promoter Score']].map(([n,l])=>`<div><strong>${n}</strong><span>${l}</span></div>`).join('')}</div>
<div class="work-features">${work.slice(0,3).map((w,i)=>`<a class="work-feature feature-${i}" href="/projects/work-${w[0]}.html"><div class="work-image"><span class="small image-label">FABITS / 0${i+1}</span><img src="/src/assets/work/${w[5]}" alt="${w[1]} interface" loading="lazy"><span class="round-arrow">↗</span></div><div class="work-info"><span class="small">${w[6]}</span><h3>${w[1]}</h3><p>${w[2]}</p><span class="read-link">Read case study ↗</span></div></a>`).join('')}</div><div class="work-list">${work.slice(3).map((w,i)=>`<a href="/projects/work-${w[0]}.html"><span class="small">0${i+4}</span><div><h3>${w[1]}</h3><p>${w[2]}</p></div><span class="small work-type">${w[6]}</span><span class="list-arrow">↗</span></a>`).join('')}</div></section>
<section id="projects" class="projects-section"><div class="section-label small"><span>02 / INDEPENDENT PROJECTS</span><span>CODE, MODELS & CIRCUITS</span></div><div class="section-heading"><h2>After hours.</h2><p>I learn by making things.<br>Some of them are useful to other people, too.</p></div><div class="project-grid">${[projects[0],projects[1],projects.find(p=>p.slug==='openupi')].map(projectCard).join('')}</div><a class="all-projects" href="/playground.html"><span>See all ${projects.length} projects</span><span>AI, tools & hardware ↗</span></a></section>
<section id="about" class="about-section"><div class="section-label small"><span>03 / ABOUT ME</span><span>A LESS DIRECT ROUTE INTO PRODUCT</span></div><div class="about-grid"><figure class="portrait"><img src="/Ashar_Photo.jpg" alt="Ashar Rai Mujeeb" loading="lazy"><figcaption class="small"><span>ASHAR RAI MUJEEB</span><span>BLR, IN ↗</span></figcaption></figure><div class="about-copy"><h2>Law first.<br>Product now.</h2><p>I moved from a legal background into product management. At Fabits, I work with designers and engineers on investment products, onboarding, and internal tools.</p><p>I’m comfortable with research, wireframes, SQL queries, and the conversations needed to ship a feature. I also write code, run a home lab, and experiment with Raspberry Pi and ESP32 projects.</p><div class="about-actions"><a class="button" href="/cv.pdf" download="Ashar-Rai-Mujeeb-CV.pdf">Download CV ↗</a><button class="text-button" id="video-open">Watch my introduction <span>▷</span></button></div><div class="experience"><span class="small">CURRENTLY</span><strong>Product Manager, Fabits</strong><span>Nov 2023 — Present · Bengaluru</span></div></div></div>
<div id="skills" class="toolkit"><h3>The toolkit</h3><div class="toolkit-grid">${[
['Product','JIRA · Confluence · Whimsical','Requirements, collaboration & planning'],['Design','Figma','Wireframes, prototypes & learning auto-layout'],['Code','Python · JavaScript','Prototyping, code reading & custom classes'],['Data','MySQL · Mixpanel','Queries, joins, extraction & analytics'],['Deployment','Google Cloud Run · AWS EC2','Deployment & learning DevOps'],['Hardware & networks','Proxmox · Twingate · Raspberry Pi','ESP32, Arduino & homelabbing']].map(([h,t,d])=>`<div><h4>${h}</h4><p>${t}</p><span>${d}</span></div>`).join('')}</div><p class="toolkit-note small">ALSO EXPLORING: CLAUDE · GENERATIVE AI · AUTOMATION</p></div>
<div class="credentials"><h3>Courses & certifications</h3>${[['NextLeap Fellowship','Top Fellow · Product Management','2023','cert1'],['Generative AI Specialization','IBM · Product Managers','2025','cert2'],['Mixpanel Certification','Product School · Analytics','2023','cert3']].map(([h,d,y,id])=>`<button class="credential" data-certificate="${id}" data-title="${h}"><span class="small">${y}</span><span><strong>${h}</strong><span>${d}</span></span><span class="credential-action">View certificate ↗</span></button>`).join('')}</div></section>${contact}
<dialog id="certificate-dialog" class="media-dialog" aria-labelledby="certificate-title"><div class="dialog-top"><h2 id="certificate-title">Certificate</h2><button class="icon-button" data-close aria-label="Close certificate">×</button></div><div class="certificate-image"><img id="certificate-image" alt=""></div><div class="dialog-bottom"><button class="button" id="certificate-prev">← Previous</button><a class="inline-link" id="certificate-download" download>Download ↗</a><button class="button" id="certificate-zoom" aria-pressed="false">Zoom</button><button class="button" id="certificate-next">Next →</button></div></dialog>
<dialog id="video-dialog" class="media-dialog" aria-label="Introduction video"><div class="dialog-top"><h2>Introduction</h2><button class="icon-button" data-close aria-label="Close video">×</button></div><div id="video-frame"></div></dialog>`;
writeFileSync(new URL('index.html',root),shell('Product manager & builder',home));
const directory=`<section class="directory"><div class="section-label small"><a href="/">← BACK TO PORTFOLIO</a><span>${String(projects.length).padStart(2,'0')} PROJECTS</span></div><h1>Built out of<br><span class="accent">curiosity.</span></h1><p class="directory-intro">AI apps, small tools, and hardware experiments.<br>Here’s what I’ve been working on outside Fabits.</p><div class="directory-controls"><div class="filters" role="group" aria-label="Filter projects">${['All','AI','Tools','Hardware'].map((f,i)=>`<button data-filter="${f}" aria-pressed="${i===0}">${f}</button>`).join('')}</div><label class="search"><span class="sr-only">Search projects</span><input id="project-search" type="search" placeholder="Search projects"><span aria-hidden="true">⌕</span></label></div><p id="project-count" class="small" role="status">${projects.length} PROJECTS</p><div class="project-grid directory-grid">${projects.map(projectCard).join('')}</div><p id="no-projects" hidden>No projects match. Try a different search or category.</p></section>`;
writeFileSync(new URL('playground.html',root),shell('Independent projects',directory,'playground'));
function articleShell(label,title,subtitle,body,sidebar){return `<section class="article-page"><div class="section-label small"><a href="${label==='FABITS'?'/#work':'/playground.html'}">← ${label==='FABITS'?'ALL WORK':'ALL PROJECTS'}</a><span>${label}</span></div><header class="article-header"><h1>${title}</h1><p>${subtitle}</p></header><div class="article-layout"><aside class="article-sidebar">${sidebar}<a class="inline-link" href="/#contact">Discuss this project ↗</a></aside><article class="prose">${body}</article></div></section>`;}
for(const p of projects.filter(project => !project.url)){
 const d=details[p.slug]||{article:p.longform||`<p>${p.description}</p>`,slides:[]};
 const media=(visualCovers[p.slug]||p.image)?`<img class="article-cover" src="${visualCovers[p.slug]||p.image}" alt="${p.name} preview">`:`<video class="article-cover" src="${p.video}" poster="${p.poster}" controls playsinline preload="metadata"></video>`;
 const slides=renderSlides(d.slides||[]);
 const body=media+((d.slides&&d.slides.length)?'':(d.article||''))+(slides?`<section class="original-slides"><h2>Project presentation</h2><p>Notes from the original project deck, kept with the decisions and trade-offs.</p>${slides}</section>`:'');
 writeFileSync(new URL(`projects/${p.slug}.html`,root),shell(p.name,articleShell(p.category.toUpperCase(),p.name,p.description,body,`<span class="small">PROJECT STATUS</span><p>${p.status}</p><span class="small">BUILT WITH</span><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div>`),p.slug,p.description));
}
for(const w of work){const data=workData[w[0]];const body=`<img class="article-cover" src="/src/assets/work/${w[5]}" alt="${w[1]} interface">`+data.slides.map((slide,i)=>`<section id="section-${i}"><span class="small">0${i+1} / ${slide.title}</span><h2>${slide.content.header}</h2>${(slide.content.metrics||[]).map(m=>`<p><strong>${m.value}</strong> ${m.label}</p>`).join('')}${(slide.content.sections||[]).map(s=>`<h3>${s.title.toLowerCase()}</h3>${s.content}`).join('')}</section>`).join('');
 writeFileSync(new URL(`projects/work-${w[0]}.html`,root),shell(w[1],articleShell('FABITS',w[1],data.subtitle,body,`<span class="small">ROLE</span><p>Product Manager</p><span class="small">COMPANY</span><p>Fabits · Bengaluru</p>${w[3]?`<strong class="article-metric">${w[3]}</strong><p>${w[4]}</p>`:''}<nav aria-label="Case study sections">${data.slides.map((s,i)=>`<a href="#section-${i}">0${i+1} · ${s.title.toLowerCase()}</a>`).join('')}</nav>`),`work-${w[0]}`,w[2]));}
console.log(`Generated homepage, project directory, ${projects.filter(project=>!project.url).length} project pages and ${work.length} case studies.`);
